apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - otel-collector.yaml
  - inventory-api.yaml
  - checkout-api.yaml
configMapGenerator:
  - name: grafana-dashboard-app-overview
    files:
      - grafana-dashboards/app-overview.json
  - name: grafana-dashboard-logs
    files:
      - grafana-dashboards/logs-explore.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
