apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-http
spec:
  selector:
    app: server
    app.kubernetes.io/instance: vms
    app.kubernetes.io/name: vms
  ports:
    - name: http
      port: 8428
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-logs-http
spec:
  selector:
    app: server
    app.kubernetes.io/instance: vls
    app.kubernetes.io/name: vls
  ports:
    - name: http
      port: 9428
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-traces-http
spec:
  selector:
    app: server
    app.kubernetes.io/instance: vts
    app.kubernetes.io/name: vts
  ports:
    - name: http
      port: 10428
      targetPort: http
